	CONFIG=configs/cuhk_sysu.yaml
	DATA_ROOT=./cuhk_market_style
	OUTPUT_DIR=./logs
	RESULT_LOG=./logs/result.txt
	cd ..;CUDA_VISIBLE_DEVICES=0  nohup python train.py --dataset cuhksysu  --cfg $CONFIG  MODEL.LOSS.USE_SOFTMAX True SOLVER.LW_RCNN_SOFTMAX_3RD 3.0 SOLVER.LW_RCNN_REID_3RD 11.0 MODEL.LOSS.LUT_SIZE 5532 MODEL.LOSS.CQ_SIZE 5000 \
	SOLVER.BASE_LR 0.0030 SOLVER.MAX_EPOCHS 351 eval_interval 10  SOLVER.LR_DECAY_MILESTONES [80,150] duke_path $DATA_ROOT \
	OUTPUT_DIR $OUTPUT_DIR > $RESULT_LOG 2>&1 &
