	CONFIG=configs/cuhk_sysu.yaml
	DATA_ROOT=./G2APS_in_market1501_style/
	OUTPUT_DIR=./logs
	RESULT_LOG=./logs/result.txt
	cd ..;CUDA_VISIBLE_DEVICES=0  nohup python train.py --cfg $CONFIG  MODEL.LOSS.USE_SOFTMAX True SOLVER.LW_RCNN_SOFTMAX_3RD 3.0 SOLVER.LW_RCNN_REID_3RD 0.5 MODEL.LOSS.LUT_SIZE 2078 MODEL.LOSS.CQ_SIZE 2000 \
	SOLVER.BASE_LR 0.0030 SOLVER.MAX_EPOCHS 300 eval_interval 10  SOLVER.LR_DECAY_MILESTONES [80,150] duke_path $DATA_ROOT \
	OUTPUT_DIR $OUTPUT_DIR   > $RESULT_LOG 2>&1 &
