	CONFIG=configs/cuhk_sysu.yaml
	DATA_ROOT=./G2APS_in_market1501_style/
	OUTPUT_DIR=./logs
	RESULT_LOG=./logs/result.txt
	cd ..; CUDA_VISIBLE_DEVICES=0  nohup python train.py --cfg $CONFIG INPUT.BATCH_SIZE_TRAIN 3 INPUT.NUM_WORKERS_TRAIN 3 MODEL.LOSS.LUT_SIZE 2078 MODEL.LOSS.CQ_SIZE 2000 \
	SOLVER.MAX_EPOCHS 300 SOLVER.BASE_LR 0.0036 eval_interval 10  SOLVER.LR_DECAY_MILESTONES [80,150] OUTPUT_DIR $OUTPUT_DIR \
	duke_path $DATA_ROOT > $RESULT_LOG 2>&1 &